[package]
name = "noidroid-cli"
description = "Command line interface for Paranoid Android."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "noidroid"
path = "src/main.rs"

[dependencies]
noidroid-core = { path = "../noidroid-core", version = "0.2.0" }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
ratatui = "0.30.2"
